apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gateway-deployment
spec:
  selector:
    matchLabels:
      component: gateway-service
      version: {{ .Chart.AppVersion }}
      deployment-id:  {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        component: gateway-service
        version: {{ .Chart.AppVersion }}
        deployment-id:  {{ .Release.Name }}
    spec:
      containers:
        - name: api-gateway
          image: ghcr.io/privateaim/node-hub-api-adapter:sha-61a1c36
          imagePullPolicy: IfNotPresent  # Maybe "Always" during debug
          readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
          ports:
            - containerPort: 5000
          env:
            - name: API_CLIENT_ID
              value: "api-client"  # To be replaced   # To be replaced
            - name: IDP_URL
              value: "https://idp.provider/"  # To be replaced
            - name: IDP_REALM
              value: "flame"  # To be replaced
            - name: RESULTS_SERVICE_URL
              value: "https://results.service.de/"  # To be replaced
            - name: HUB_SERVICE_URL
              value: "https://central.hub.service.de/"  # To be replaced
            - name: K8S_API_KEY
              value: "apiSecret"  # To be replaced
