# Only created if idp.existingSecret not defined

{{- if not .Values.idp.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-hub-adapter-keycloak-secret
data:
  static: cFR2THJCS3V5MHZ4cnV2VXByd3NYcEV0dzg0ZEROOUM= # Same as hardcoded secret in keycloak init realm, for testing
  hub-adapter-kc-secret: {{ randAlphaNum 30 | b64enc | quote }}
{{- end }}
