version: '3.3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: testkeycloakdb
      POSTGRES_USER: testkeycloakuser
      POSTGRES_PASSWORD: testkeycloakpassword
    restart:
      always

  keycloak:
    # Have to use 22.0.0 for realm import. TODO: figure how to import realm config with 23+
    image: quay.io/keycloak/keycloak:22.0.0
    volumes:
      - ./test-realm.json:/opt/keycloak/data/import/realm-export.json
    command:
      - "start-dev --import-realm"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: testkeycloakdb
      DB_USER: testkeycloakuser
      DB_SCHEMA: public
      DB_PASSWORD: testkeycloakpassword
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_USER: keycloakuser
      KEYCLOAK_PASSWORD: keycloakpassword
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_LOGLEVEL: DEBUG
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    restart:
      always

  minio:
    image: quay.io/minio/minio:RELEASE.2024-01-16T16-07-38Z
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=s3cr3t_p4ssw0rd
      - MINIO_LOCAL_BUCKET_NAME=flame
      - MINIO_REMOTE_BUCKET_NAME=upload
    ports:
      - "9000:9000"  # s3 api
      - "9001:9001"  # web console
    command: [ "server", "--address", ":9000", "--console-address", ":9001" ]
