keycloak:
  auth:
    adminUser: admin
    adminPassword: admin
  postgresql:
    enabled: true
    nameOverride: keycloak-postgresql
    auth:
      postgresPassword: ""
      username: keycloak  # custom user
      password: keycloak  # custom user pwd
      database: keycloak
      # existingSecret: "kc-password-secret"  # admin password, requires "password" key in secret
    architecture: standalone

  keycloakConfigCli:
    ## @param keycloakConfigCli.enabled Whether to enable keycloak-config-cli job
    ## Must be set to true to apply settings below
    enabled: true
    ## @param keycloakConfigCli.configuration keycloak-config-cli realms configuration
    ## NOTE: nil keys will be considered files to import locally
    ## Example:
    ## configuration:
    ##   realm1.json: |
    ##     {
    ##       "realm": "realm1",
    ##       "clients": []
    ##     }
    ##   files/realm2.yaml:
    ##   realm3.yaml: |
    ##     realm: realm3
    ##     clients: []
    ##
    existingConfigmap: "flame-default-realm"
