name: Build docker Image
description: Build and tag specific Docker images

inputs:
  platforms:
    default: linux/amd64
    description: "The platform(s) to build (CSV)"
    required: true
  docker_file:
    default: ./Dockerfile
    description: "The Dockerfile to use"
    required: false
  image_tags:
    default: ""
    description: "The tags to apply to the image"
    required: false
  push:
    default: "false"
    description: "Push the image to the registries"
    required: false
  token:
    description: "Github token"
    required: true
  tag_suffix:
    default: ""
    description: "Suffix to append to the image tags"
    required: false

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf  # tag=v3.2.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    #      - name: Login to Docker Hub
    #        if: inputs.push == true
    #        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567  # tag=v3.3.0
    #        with:
    #          username: ${{ secrets.docker_username }}
    #          password: ${{ secrets.docker_password }}

    - name: Login to GitHub Container Registry
      if: ${{ inputs.push == 'true' }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        context: git
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=sha
          type=raw,value=canary,enable=${{ github.event_name == 'workflow_dispatch' }}
          type=raw,event=workflow_dispatch,value=${{ github.event.inputs.dispatch-tag }}
          type=semver,pattern={{version}},value=${{ inputs.image_tags }},branch=main

    - name: Clean variables
      id: clean
      shell: bash
      run: |
        # Replace illegal characters in tag suffix
        echo suffix=$(echo "${{ inputs.tag_suffix }}" | sed -e 's/[^a-zA-Z0-9._-]/_/g') >> $GITHUB_OUTPUT

    - name: Add suffix to image tags
      id: tag_suffix
      shell: bash
      run: |
        delimiter="$(openssl rand -hex 8)"
        echo "tags<<${delimiter}" >> $GITHUB_OUTPUT
        # if tag_suffix is set, append it to each tag
        if [[ -n "${{ inputs.tag_suffix }}" ]]; then
          echo "${{ steps.meta.outputs.tags }}" | sed -e "s/$/-${{ steps.clean.outputs.suffix }}/" >> $GITHUB_OUTPUT
        else
          echo "${{ steps.meta.outputs.tags }}" >> $GITHUB_OUTPUT
        fi
        echo "${delimiter}" >> $GITHUB_OUTPUT

    - name: Build image for push
      uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355  # tag=v6.10.0
      with:
        file: ${{ inputs.docker_file }}
        tags: ${{ steps.tag_suffix.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push == 'true' }}

