"""Expected routes and their configurations for each router."""

from flame_hub._core_client import Analysis, AnalysisBucket, AnalysisNode, Node, Project, ProjectNode, RegistryProject
from kong_admin_client import Service

from hub_adapter.schemas.hub import AnalysisImageUrl, DetailedAnalysis, NodeTypeResponse
from hub_adapter.schemas.kong import (
    DeleteProject,
    DeleteService,
    LinkDataStoreProject,
    LinkProjectAnalysis,
    ListConsumers,
    ListRoutes,
    ListServices,
)
from hub_adapter.schemas.podorc import (
    CleanupPodResponse,
    LogResponse,
    PodProgressResponse,
    PodResponse,
    StatusOnlyResponse,
)

EXPECTED_META_ROUTE_CONFIG = (
    {
        "name": "initialize_analysis",
        "path": "/analysis/initialize",
        "methods": {"POST"},
        "response_model": StatusOnlyResponse,
        "status_code": 201,
    },
    {
        "name": "terminate_analysis",
        "path": "/analysis/terminate/{analysis_id}",
        "methods": {"DELETE"},
        "response_model": StatusOnlyResponse,
        "status_code": 200,
    },
)

EXPECTED_STORAGE_ROUTE_CONFIG = (
    {
        "path": "/local",
        "name": "delete_local_results",
        "methods": {"DELETE"},
        "status_code": 200,
        "response_model": None,
    },
)

EXPECTED_KONG_ROUTE_CONFIG = (
    {
        "name": "list_data_stores",
        "path": "/kong/datastore",
        "methods": {"GET"},
        "response_model": ListServices,
        "status_code": 200,
    },
    {
        "name": "kong.datastore.delete_orphaned",
        "path": "/kong/datastore",
        "methods": {"DELETE"},
        "response_model": DeleteService,
        "status_code": 200,
    },
    {
        "name": "list_specific_data_store",
        "path": "/kong/datastore/{project_id}",
        "methods": {"GET"},
        "response_model": ListServices,
        "status_code": 200,
    },
    {
        "name": "delete_data_store",
        "path": "/kong/datastore/{data_store_name}",
        "methods": {"DELETE"},
        "response_model": None,
        "status_code": 200,
    },
    {
        "name": "create_service",
        "path": "/kong/datastore",
        "methods": {"POST"},
        "response_model": Service,
        "status_code": 201,
    },
    {
        "name": "list_projects",
        "path": "/kong/project",
        "methods": {"GET"},
        "response_model": ListRoutes,
        "status_code": 200,
    },
    {
        "name": "list_specific_project",
        "path": "/kong/project/{project_id}",
        "methods": {"GET"},
        "response_model": ListRoutes,
        "status_code": 200,
    },
    {
        "name": "create_route_to_datastore",
        "path": "/kong/project",
        "methods": {"POST"},
        "response_model": LinkDataStoreProject,
        "status_code": 201,
    },
    {
        "name": "create_datastore_and_project_with_link",
        "path": "/kong/initialize",
        "methods": {"POST"},
        "response_model": LinkDataStoreProject,
        "status_code": 201,
    },
    {
        "name": "delete_route",
        "path": "/kong/project/{project_route_id}",
        "methods": {"DELETE"},
        "response_model": DeleteProject,
        "status_code": 200,
    },
    {
        "name": "list_analyses",
        "path": "/kong/analysis",
        "methods": {"GET"},
        "response_model": ListConsumers,
        "status_code": 200,
    },
    {
        "name": "list_specific_analysis",
        "path": "/kong/analysis/{analysis_id}",
        "methods": {"GET"},
        "response_model": ListConsumers,
        "status_code": 200,
    },
    {
        "name": "create_and_connect_analysis_to_project",
        "path": "/kong/analysis",
        "methods": {"POST"},
        "response_model": LinkProjectAnalysis,
        "status_code": 201,
    },
    {
        "name": "delete_analysis",
        "path": "/kong/analysis/{analysis_id}",
        "methods": {"DELETE"},
        "response_model": None,
        "status_code": 200,
    },
    {
        "name": "probe_connection",
        "path": "/kong/project/{project_id}/{ds_type}/health",
        "methods": {"GET"},
        "response_model": None,
        "status_code": 200,
    },
)
EXPECTED_HUB_ROUTE_CONFIG = (
    {
        "path": "/projects",
        "name": "list_all_projects",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": list[Project],
    },
    {
        "path": "/projects/{project_id}",
        "name": "list_specific_project",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": Project,
    },
    {
        "path": "/project-nodes",
        "name": "list_project_proposals",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": list[ProjectNode],
    },
    {
        "path": "/project-nodes/{project_node_id}",
        "name": "list_project_proposal",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": ProjectNode,
    },
    {
        "path": "/project-nodes/{project_node_id}",
        "name": "accept_reject_project_proposal",
        "methods": {"POST"},
        "status_code": 200,
        "response_model": ProjectNode,
    },
    {
        "path": "/analysis-nodes",
        "name": "list_analysis_nodes",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": list[AnalysisNode],
    },
    {
        "path": "/analysis-nodes/{analysis_node_id}",
        "name": "list_specific_analysis_node",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": AnalysisNode,
    },
    {
        "path": "/analysis-nodes/{analysis_node_id}",
        "name": "accept_reject_analysis_node",
        "methods": {"POST"},
        "status_code": 200,
        "response_model": AnalysisNode,
    },
    {
        "path": "/analyses",
        "name": "list_all_analyses",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": list[Analysis],
    },
    {
        "path": "/analyses/{analysis_id}",
        "name": "list_specific_analysis",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": Analysis,
    },
    {"path": "/nodes", "name": "list_all_nodes", "methods": {"GET"}, "status_code": 200, "response_model": list[Node]},
    {
        "path": "/nodes/{node_id}",
        "name": "list_specific_node",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": Node,
    },
    {
        "path": "/node-type",
        "name": "get_node_type",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": NodeTypeResponse,
    },
    {
        "path": "/analyses/{analysis_id}",
        "name": "update_specific_analysis",
        "methods": {"POST"},
        "status_code": 200,
        "response_model": DetailedAnalysis,
    },
    {
        "path": "/registry-projects/{registry_project_id}",
        "name": "get_registry_metadata_for_project",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": RegistryProject,
    },
    {
        "path": "/analysis/image",
        "name": "get_analysis_image_url",
        "methods": {"POST"},
        "status_code": None,
        "response_model": AnalysisImageUrl,
    },
    {
        "path": "/analysis-buckets",
        "name": "list_all_analysis_buckets",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": None,
    },
    {
        "path": "/analysis-buckets/{analysis_bucket_id}",
        "name": "list_specific_analysis_buckets",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": AnalysisBucket,
    },
    {
        "path": "/analysis-bucket-files",
        "name": "list_all_analysis_bucket_files",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": None,
    },
    {
        "path": "/analysis-bucket-files/{analysis_bucket_file_id}",
        "name": "list_specific_analysis_bucket_file",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": None,
    },
)
EXPECTED_PO_ROUTE_CONFIG = (
    {
        "name": "create_analysis",
        "path": "/po",
        "methods": {"POST"},
        "response_model": StatusOnlyResponse,
        "status_code": 200,
    },
    {
        "name": "get_all_analysis_logs",
        "path": "/po/logs",
        "methods": {"GET"},
        "response_model": LogResponse,
        "status_code": 200,
    },
    {
        "name": "get_analysis_logs",
        "path": "/po/logs/{analysis_id}",
        "methods": {"GET"},
        "response_model": LogResponse,
        "status_code": 200,
    },
    {
        "name": "get_all_analysis_log_history",
        "path": "/po/history",
        "methods": {"GET"},
        "response_model": LogResponse,
        "status_code": 200,
    },
    {
        "name": "get_analysis_log_history",
        "path": "/po/history/{analysis_id}",
        "methods": {"GET"},
        "response_model": LogResponse,
        "status_code": 200,
    },
    {
        "name": "get_all_analysis_status",
        "path": "/po/status",
        "methods": {"GET"},
        "response_model": PodProgressResponse,
        "status_code": 200,
    },
    {
        "name": "get_analysis_status",
        "path": "/po/status/{analysis_id}",
        "methods": {"GET"},
        "response_model": PodProgressResponse,
        "status_code": 200,
    },
    {
        "name": "get_all_analysis_pods",
        "path": "/po/pods",
        "methods": {"GET"},
        "response_model": PodResponse,
        "status_code": 200,
    },
    {
        "name": "get_analysis_pods",
        "path": "/po/pods/{analysis_id}",
        "methods": {"GET"},
        "response_model": PodResponse,
        "status_code": 200,
    },
    {
        "name": "stop_all_analyses",
        "path": "/po/stop",
        "methods": {"PUT"},
        "response_model": StatusOnlyResponse,
        "status_code": 200,
    },
    {
        "name": "stop_analysis",
        "path": "/po/stop/{analysis_id}",
        "methods": {"PUT"},
        "response_model": StatusOnlyResponse,
        "status_code": 200,
    },
    {
        "name": "delete_all_analyses",
        "path": "/po/delete",
        "methods": {"DELETE"},
        "response_model": StatusOnlyResponse,
        "status_code": 200,
    },
    {
        "name": "delete_analysis",
        "path": "/po/delete/{analysis_id}",
        "methods": {"DELETE"},
        "response_model": StatusOnlyResponse,
        "status_code": 200,
    },
    {
        "name": "cleanup_node",
        "path": "/po/cleanup/{cleanup_type}",
        "methods": {"DELETE"},
        "response_model": CleanupPodResponse,
        "status_code": 200,
    },
)
