"""Expected routes and their configurations for each router."""

from flame_hub._core_client import Analysis, AnalysisBucket, AnalysisNode, Node, Project, ProjectNode, RegistryProject
from kong_admin_client import Service

from hub_adapter.models.events import EventLogResponse
from hub_adapter.models.hub import AnalysisImageUrl, DetailedAnalysis, NodeTypeResponse
from hub_adapter.models.kong import (
    DeleteProject,
    LinkDataStoreProject,
    LinkProjectAnalysis,
    ListConsumers,
    ListRoutes,
    ListServices,
)
from hub_adapter.models.podorc import CleanupPodResponse, LogResponse, PodResponse, StatusResponse

EXPECTED_EVENT_ROUTE_CONFIG = (
    {
        "name": "events.get",
        "path": "/events",
        "methods": {"GET"},
        "response_model": list[EventLogResponse],
        "status_code": 200,
    },
)

EXPECTED_META_ROUTE_CONFIG = (
    {
        "name": "meta.initialize",
        "path": "/analysis/initialize",
        "methods": {"POST"},
        "response_model": StatusResponse,
        "status_code": 201,
    },
    {
        "name": "meta.terminate",
        "path": "/analysis/terminate/{analysis_id}",
        "methods": {"DELETE"},
        "response_model": StatusResponse,
        "status_code": 200,
    },
)

EXPECTED_RESULTS_ROUTE_CONFIG = (
    {
        "path": "/local",
        "name": "storage.local.delete",
        "methods": {"DELETE"},
        "status_code": 200,
        "response_model": None,
    },
)

EXPECTED_KONG_ROUTE_CONFIG = (
    {
        "name": "kong.datastore.get",
        "path": "/kong/datastore",
        "methods": {"GET"},
        "response_model": ListServices,
        "status_code": 200,
    },
    {
        "name": "kong.datastore.get",
        "path": "/kong/datastore/{project_id}",
        "methods": {"GET"},
        "response_model": ListServices,
        "status_code": 200,
    },
    {
        "name": "kong.datastore.delete",
        "path": "/kong/datastore/{data_store_name}",
        "methods": {"DELETE"},
        "response_model": None,
        "status_code": 200,
    },
    {
        "name": "kong.datastore.create",
        "path": "/kong/datastore",
        "methods": {"POST"},
        "response_model": Service,
        "status_code": 201,
    },
    {
        "name": "kong.project.get",
        "path": "/kong/project",
        "methods": {"GET"},
        "response_model": ListRoutes,
        "status_code": 200,
    },
    {
        "name": "kong.project.get",
        "path": "/kong/project/{project_id}",
        "methods": {"GET"},
        "response_model": ListRoutes,
        "status_code": 200,
    },
    {
        "name": "kong.project.create",
        "path": "/kong/project",
        "methods": {"POST"},
        "response_model": LinkDataStoreProject,
        "status_code": 201,
    },
    {
        "name": "kong.initialize",
        "path": "/kong/initialize",
        "methods": {"POST"},
        "response_model": LinkDataStoreProject,
        "status_code": 201,
    },
    {
        "name": "kong.project.delete",
        "path": "/kong/project/{project_route_id}",
        "methods": {"DELETE"},
        "response_model": DeleteProject,
        "status_code": 200,
    },
    {
        "name": "kong.analysis.get",
        "path": "/kong/analysis",
        "methods": {"GET"},
        "response_model": ListConsumers,
        "status_code": 200,
    },
    {
        "name": "kong.analysis.get",
        "path": "/kong/analysis/{analysis_id}",
        "methods": {"GET"},
        "response_model": ListConsumers,
        "status_code": 200,
    },
    {
        "name": "kong.analysis.create",
        "path": "/kong/analysis",
        "methods": {"POST"},
        "response_model": LinkProjectAnalysis,
        "status_code": 201,
    },
    {
        "name": "kong.analysis.delete",
        "path": "/kong/analysis/{analysis_id}",
        "methods": {"DELETE"},
        "response_model": None,
        "status_code": 200,
    },
    {
        "name": "kong.probe",
        "path": "/kong/project/{project_id}/{ds_type}/health",
        "methods": {"GET"},
        "response_model": None,
        "status_code": 200,
    },
)
EXPECTED_HUB_ROUTE_CONFIG = (
    {
        "path": "/projects",
        "name": "hub.project.get",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": list[Project],
    },
    {
        "path": "/projects/{project_id}",
        "name": "hub.project.get",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": Project,
    },
    {
        "path": "/project-nodes",
        "name": "hub.project.node.get",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": list[ProjectNode],
    },
    {
        "path": "/project-nodes/{project_node_id}",
        "name": "hub.project.node.get",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": ProjectNode,
    },
    {
        "path": "/project-nodes/{project_node_id}",
        "name": "hub.project.node.update",
        "methods": {"POST"},
        "status_code": 200,
        "response_model": ProjectNode,
    },
    {
        "path": "/analysis-nodes",
        "name": "hub.analysis.node.get",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": list[AnalysisNode],
    },
    {
        "path": "/analysis-nodes/{analysis_node_id}",
        "name": "hub.analysis.node.get",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": AnalysisNode,
    },
    {
        "path": "/analysis-nodes/{analysis_node_id}",
        "name": "hub.analysis.node.update",
        "methods": {"POST"},
        "status_code": 200,
        "response_model": AnalysisNode,
    },
    {
        "path": "/analyses",
        "name": "hub.analysis.get",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": list[Analysis],
    },
    {
        "path": "/analyses/{analysis_id}",
        "name": "hub.analysis.get",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": Analysis,
    },
    {"path": "/nodes", "name": "hub.node.get", "methods": {"GET"}, "status_code": 200, "response_model": list[Node]},
    {
        "path": "/nodes/{node_id}",
        "name": "hub.node.get",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": Node,
    },
    {
        "path": "/node-type",
        "name": "hub.node.type.get",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": NodeTypeResponse,
    },
    {
        "path": "/analyses/{analysis_id}",
        "name": "hub.analysis.update",
        "methods": {"POST"},
        "status_code": 200,
        "response_model": DetailedAnalysis,
    },
    {
        "path": "/registry-projects/{registry_project_id}",
        "name": "hub.registry.metadata.get",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": RegistryProject,
    },
    {
        "path": "/analysis/image",
        "name": "hub.analysis.image.get",
        "methods": {"POST"},
        "status_code": None,
        "response_model": AnalysisImageUrl,
    },
    {
        "path": "/analysis-buckets",
        "name": "hub.analysis.bucket.get",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": None,
    },
    {
        "path": "/analysis-buckets/{analysis_bucket_id}",
        "name": "hub.analysis.bucket.get",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": AnalysisBucket,
    },
    {
        "path": "/analysis-bucket-files",
        "name": "hub.analysis.bucket.file.get",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": None,
    },
    {
        "path": "/analysis-bucket-files/{analysis_bucket_file_id}",
        "name": "hub.analysis.bucket.file.get",
        "methods": {"GET"},
        "status_code": 200,
        "response_model": None,
    },
)
EXPECTED_PO_ROUTE_CONFIG = (
    {
        "name": "podorc.pods.create",
        "path": "/po",
        "methods": {"POST"},
        "response_model": StatusResponse,
        "status_code": 200,
    },
    {
        "name": "podorc.logs.get",
        "path": "/po/logs",
        "methods": {"GET"},
        "response_model": LogResponse,
        "status_code": 200,
    },
    {
        "name": "podorc.logs.get",
        "path": "/po/logs/{analysis_id}",
        "methods": {"GET"},
        "response_model": LogResponse,
        "status_code": 200,
    },
    {
        "name": "podorc.history.get",
        "path": "/po/history",
        "methods": {"GET"},
        "response_model": LogResponse,
        "status_code": 200,
    },
    {
        "name": "podorc.history.get",
        "path": "/po/history/{analysis_id}",
        "methods": {"GET"},
        "response_model": LogResponse,
        "status_code": 200,
    },
    {
        "name": "podorc.status.get",
        "path": "/po/status",
        "methods": {"GET"},
        "response_model": StatusResponse,
        "status_code": 200,
    },
    {
        "name": "podorc.status.get",
        "path": "/po/status/{analysis_id}",
        "methods": {"GET"},
        "response_model": StatusResponse,
        "status_code": 200,
    },
    {
        "name": "podorc.pods.get",
        "path": "/po/pods",
        "methods": {"GET"},
        "response_model": PodResponse,
        "status_code": 200,
    },
    {
        "name": "podorc.pods.get",
        "path": "/po/pods/{analysis_id}",
        "methods": {"GET"},
        "response_model": PodResponse,
        "status_code": 200,
    },
    {
        "name": "podorc.pods.stop",
        "path": "/po/stop",
        "methods": {"PUT"},
        "response_model": StatusResponse,
        "status_code": 200,
    },
    {
        "name": "podorc.pods.stop",
        "path": "/po/stop/{analysis_id}",
        "methods": {"PUT"},
        "response_model": StatusResponse,
        "status_code": 200,
    },
    {
        "name": "podorc.pods.delete",
        "path": "/po/delete",
        "methods": {"DELETE"},
        "response_model": StatusResponse,
        "status_code": 200,
    },
    {
        "name": "podorc.pods.delete",
        "path": "/po/delete/{analysis_id}",
        "methods": {"DELETE"},
        "response_model": StatusResponse,
        "status_code": 200,
    },
    {
        "name": "podorc.cleanup",
        "path": "/po/cleanup/{cleanup_type}",
        "methods": {"DELETE"},
        "response_model": CleanupPodResponse,
        "status_code": 200,
    },
)
