name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-please:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.release.outputs.release_created }}
      version: ${{ steps.release.outputs.version }}
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        name: release-please
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build-prod-image:
    name: Build and push production Docker image
    if: ${{ needs.release-please.outputs.released == 'true' }}
    needs: release-please  # Wait until pkg bumped
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout  # required for finding action
        uses: actions/checkout@v4

      - name: Build production image
        uses: ./.github/actions/build-docker-image
        with:
          platforms: linux/amd64
          docker_file: Dockerfile
          image_tags: ${{ needs.release-please.outputs.version }}
          push: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}

  build-canary-image:
    name: Build and push canary image
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout  # required for finding action
        uses: actions/checkout@v4

      - name: Build canary image
        uses: ./.github/actions/build-docker-image
        with:
          platforms: linux/amd64
          docker_file: Dockerfile
          push: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}
