name: Build and push Docker images

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: read # for checkout

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bump:
    name: "Bump Version"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.poetry_bump.outputs.new_version }}
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@foobar.com"

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install poetry
        uses: abatilo/actions-poetry@v4

      - name: Bump
        id: poetry_bump
        run: |
          echo "new_version=$(poetry version patch | grep -o -E '[0-9]\.[0-9]\.[0-9]$')" >> $GITHUB_OUTPUT

      - name: Push
        run: |
          git add pyproject.toml
          git commit -m "ci: version bump to ${{ steps.poetry_bump.outputs.new_version }}"
          git push

  build-prod-image:
    name: Build and push production Docker image
    needs: bump  # Wait until pkg bumped
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout  # required for finding action
        uses: actions/checkout@v4

      - name: Build production image
        uses: ./.github/actions/build-docker-image
        with:
          platforms: linux/amd64
          docker_file: Dockerfile
          image_tags: ${{ needs.bump.outputs.version }}
          push: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}

  build-canary-image:
    name: Build and push canary image
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout  # required for finding action
        uses: actions/checkout@v4

      - name: Build canary image
        uses: ./.github/actions/build-docker-image
        with:
          platforms: linux/amd64
          docker_file: Dockerfile
          push: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}
